# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completion',
            new_name='progress',
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
